# Gotify
# Addtional image tag: latest
# https://hub.docker.com/r/gotify/server

version: "3.4" # this must match the version in docker-compose.yml
services:
  gotify:
    image: gotify/server
    container_name: gotify
    ports:
      - 27798:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=RANDOMPASSWORD
    volumes:
      - ${DOCKERCONFDIR}/gotify:/app/data