# MySQL
# Addtional image tag: latest
# https://hub.docker.com/_/mysql

version: "3.4" # this must match the version in docker-compose.yml
services:
  mysql-server:
    container_name: mysql-server
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=somepassword