# Ombi
# Addtional image tag: v4
# https://hub.docker.com/r/hotio/ombi

version: "3.4" # this must match the version in docker-compose.yml
services:
  ombi-v4:
    container_name: ombi-v4
    image: hotio/ombi:v4-4.0.331 # change tag on each new build
    ports:
      - "5000:5000"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
      - ${DOCKERCONFDIR}/ombi-v4:/config