# Radarr
# Addtional image tag: preview
# https://hub.docker.com/r/linuxserver/radarr

version: "3.4" # this must match the version in docker-compose.yml
services:
  radarrpreview:
    container_name: radarrpreview
    image: linuxserver/radarr:preview
    hostname: ${DOCKERHOSTNAME}
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
  
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
    - 7878:7878
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/radarrpreview:/config
    - /path/to/media/storage:/path/to/container/media/directory