# Readarr
# Addtional image tag: none (EACH BUILD WILL REQUIRE INTERNAL DB RESET)
# https://hub.docker.com/r/hotio/readarr

version: "3.4" # this must match the version in docker-compose.yml
services:
  readarr:
    container_name: readarr
    image: hotio/readarr
    hostname: ${DOCKERHOSTNAME}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    ports:
      - 8787:8787
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
      - ${DOCKERCONFDIR}/readarr:/config