# Speedtest Double Commander
# Addtional image tag: none
# https://hub.docker.com/r/linuxserver/doublecommander

version: "3.4" # this must match the version in docker-compose.yml
services:
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    hostname: ${DOCKERHOSTNAME}
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - OOKLA_EULA_GDPR=true
    ports:
      - "8765:80"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    volumes:
      - ${DOCKERCONFDIR}/speedtest/config:/config