# Traktarr
# Addtional image tag: none
# https://hub.docker.com/r/cloudb0x/traktarr

version: "3.4" # this must match the version in docker-compose.yml
services:
  traktarr:
    image: cloudb0x/traktarr
    container_name: traktarr
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/traktarr:/config
      - ${DOCKERSHAREDDIR}:/shared
    command: run --run-now
